CREATE TABLE IF NOT EXISTS subtitle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    start_time_ms INTEGER NOT NULL,
    end_time_ms INTEGER NOT NULL,
    text TEXT NOT NULL,
    user_id uuid NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_subtitle_user_name ON subtitle(user_id, name);
CREATE INDEX IF NOT EXISTS idx_subtitle_user_name_time ON subtitle(user_id, name, start_time_ms);
