CREATE TABLE subtitle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    start_time_ms INTEGER NOT NULL,
    end_time_ms INTEGER NOT NULL,
    text TEXT NOT NULL,
    user_id uuid NOT NULL
);

CREATE INDEX idx_subtitle_user ON subtitle(user_id);
CREATE INDEX idx_subtitle_name ON subtitle(name);
