#!/bin/bash
set -e

# FAANG Senior Pattern: Idempotent Database Initialization
# This script ensures that users, databases, and schemas exist regardless of the volume state.

echo "Starting FAANG-standard database initialization..."

# Use local socket connection (trusted internally) to ensure the root password matches our env
# This handles the case where the volume was created with a different password.
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    -- Ensure the postgres user has the correct password from environment
    ALTER USER postgres WITH PASSWORD '$POSTGRES_PASSWORD';
    
    -- Create dedicated application user
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_user WHERE usename = 'substream_app') THEN
            CREATE USER substream_app WITH PASSWORD 'substream_pass';
        END IF;
    END
    \$\$;

    -- Create databases
    SELECT 'CREATE DATABASE sse_iam' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'sse_iam')\gexec
    SELECT 'CREATE DATABASE substreamedu_dictionary' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'substreamedu_dictionary')\gexec
    SELECT 'CREATE DATABASE substreamedu_media' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'substreamedu_media')\gexec
    
    -- Grant privileges
    GRANT ALL PRIVILEGES ON DATABASE sse_iam TO substream_app;
    GRANT ALL PRIVILEGES ON DATABASE substreamedu_dictionary TO substream_app;
    GRANT ALL PRIVILEGES ON DATABASE substreamedu_media TO substream_app;
EOSQL

# Function to initialize a specific database
init_db_permissions() {
    local db_name=$1
    echo "Granting schema permissions on $db_name to substream_app..."
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$db_name" <<-EOSQL
        GRANT ALL ON SCHEMA public TO substream_app;
EOSQL
}

init_db_permissions "sse_iam"
init_db_permissions "substreamedu_dictionary"
init_db_permissions "substreamedu_media"

# The following blocks should ideally be managed by a migration tool (e.g. migrate or liquibase)
# For now, we ensure basic tables exist.

# IAM Service
psql -v ON_ERROR_STOP=1 --username "substream_app" --dbname "sse_iam" <<-EOSQL
    CREATE TABLE IF NOT EXISTS sse_user (
        id uuid PRIMARY KEY,
        email varchar(64) UNIQUE NOT NULL,
        is_active boolean DEFAULT true,
        telegram_token varchar(255),
        is_premium boolean NOT NULL DEFAULT false,
        translation_count integer DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
EOSQL

# Dictionary Service
# Create extensions as superuser since CREATE EXTENSION requires superuser privileges
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "substreamedu_dictionary" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
EOSQL

psql -v ON_ERROR_STOP=1 --username "substream_app" --dbname "substreamedu_dictionary" <<-EOSQL
    CREATE TABLE IF NOT EXISTS dictionary (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id uuid NOT NULL,
        resource_name varchar(255) NOT NULL,
        highlighted_text text NOT NULL,
        translated_text text,
        context text,
        extended_context text,
        note varchar(255),
        transcription varchar(255),
        definition text,
        image_url varchar(255),
        status varchar(50) DEFAULT 'new',
        repetition_level integer DEFAULT 0,
        consecutive_success integer DEFAULT 0,
        next_repetition_date date,
        interval float DEFAULT 0,
        ease_factor float DEFAULT 2.5,
        hard_count integer DEFAULT 0,
        lapses integer DEFAULT 0,
        learning_step integer DEFAULT 0,
        learning_due timestamp,
        last_reviewed date,
        total_reviews integer DEFAULT 0,
        correct_reviews integer DEFAULT 0,
        retention_rate float DEFAULT 0.0,
        avg_review_duration integer DEFAULT 0,
        best_review_time time,
        difficulty_score float DEFAULT 0.0,
        is_leech boolean DEFAULT false,
        stability float DEFAULT 0.0,
        retrievability float DEFAULT 0.0,
        rolling_retention float DEFAULT 0.0,
        card_type integer DEFAULT 0,
        created_on timestamp DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX IF NOT EXISTS idx_dictionary_user_id ON dictionary (user_id);
    CREATE INDEX IF NOT EXISTS idx_dictionary_srs ON dictionary (user_id, status, next_repetition_date);
    CREATE INDEX IF NOT EXISTS idx_dictionary_learning_due ON dictionary (user_id, status, learning_due);
    CREATE INDEX IF NOT EXISTS idx_dictionary_pagination ON dictionary (user_id, card_type, id);
    CREATE INDEX IF NOT EXISTS idx_dictionary_resource_name_trgm ON dictionary USING gin (resource_name gin_trgm_ops);

    CREATE TABLE IF NOT EXISTS review_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id uuid NOT NULL,
        card_id bigint NOT NULL,
        reviewed_at timestamp NOT NULL,
        rating integer NOT NULL,
        response_time_ms integer NOT NULL,
        stability_before float NOT NULL,
        difficulty_before float NOT NULL,
        elapsed_days float NOT NULL,
        scheduled_days float NOT NULL,
        state varchar(50) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS user_srs_parameters (
        user_id uuid PRIMARY KEY,
        w0 float, w1 float, w2 float, w3 float, w4 float, w5 float, 
        w6 float, w7 float, w8 float, w9 float, w10 float, w11 float, w12 float,
        last_optimized timestamp DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS outbox_events (
        id UUID PRIMARY KEY,
        aggregate_id VARCHAR(255) NOT NULL,
        type VARCHAR(255) NOT NULL,
        payload TEXT NOT NULL,
        topic VARCHAR(255) NOT NULL,
        created_at TIMESTAMP NOT NULL,
        processed_at TIMESTAMP,
        status VARCHAR(20) NOT NULL
    );

    CREATE INDEX IF NOT EXISTS idx_outbox_events_status_created ON outbox_events(status, created_at);
    CREATE INDEX IF NOT EXISTS idx_review_log_user_date ON review_log(user_id, reviewed_at DESC);
    CREATE INDEX IF NOT EXISTS idx_review_log_user_card ON review_log(user_id, card_id);
    CREATE INDEX IF NOT EXISTS idx_dictionary_user_cardtype_status ON dictionary(user_id, card_type, status);

    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO substream_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO substream_app;
EOSQL

# Media Service
psql -v ON_ERROR_STOP=1 --username "substream_app" --dbname "substreamedu_media" <<-EOSQL
    CREATE TABLE IF NOT EXISTS subtitle (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        start_time_ms INTEGER NOT NULL,
        end_time_ms INTEGER NOT NULL,
        text TEXT NOT NULL,
        user_id uuid NOT NULL
    );
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO substream_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO substream_app;
EOSQL

echo "Database initialization completed successfully!"
