server {
    listen 80 default_server;
    server_name _;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    location / {
        return 200 'Nginx Bootstrap UP! Waiting for SSL...';
        add_header Content-Type text/plain;
    }
}
