/** @type {import('tailwindcss').Config} */
// eslint-disable-next-line no-undef
module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './node_modules/react-tailwindcss-datepicker/dist/index.esm.js',
  ],
  theme: {
    extend: {
      animation: {
        fadeIn: 'fadeIn 0.3s ease-in-out',
        marquee: 'marqueeScroll 40s linear infinite',
        'spin-slow': 'spin 20s linear infinite',
        float: 'float 6s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        marqueeScroll: {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-50%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
      fontFamily: {
        sans: ['"e-Ukraine"', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        body: ['"e-Ukraine"', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        heading: ['"e-UkraineHead"', 'Nunito', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['"e-UkraineHead"', 'Nunito', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'Courier New', 'monospace'],
      },
      colors: {
        /* Warm Cinematic Espresso Theme Tokens (bind to src/index.css) */
        canvas: 'var(--color-canvas)',
        surface: 'var(--color-surface)',
        'surface-elevated': 'var(--color-surface-elevated)',
        'surface-soft': 'var(--color-surface)',
        'surface-card': 'var(--color-surface)',
        'surface-dark': 'var(--color-surface-elevated)',

        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',

        ink: 'var(--color-ink)',
        'ink-deep': 'var(--color-ink)',
        body: 'var(--color-body)',
        'body-text': 'var(--color-body)',
        mute: 'var(--color-mute)',

        hairline: 'var(--color-hairline)',
        'hairline-strong': 'var(--color-hairline-strong)',

        /* Accent & feedback */
        accent: '#6366f1',
        'accent-light': '#818cf8',
        'accent-glow': 'rgba(99,102,241,0.12)',
        'accent-subtle': 'rgba(99,102,241,0.08)',
        'focus-ring': 'rgba(0, 69, 230, 0.5)',
        'terminal-red': '#ff5f56',
        'terminal-yellow': '#ffbd2e',
        'terminal-green': '#27c93f',
      },
      borderRadius: {
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '20px',
        '3xl': '24px',
        '4xl': '32px',
        'full': '9999px',
      },
      boxShadow: {
        'sm': 'none',
        'md': 'none',
        'lg': 'none',
        'xl': 'none',
        '2xl': 'none',
        '3xl': 'none',
        'drop-shadow-glow': 'none',
        'premium': '0 1px 2px rgba(0,0,0,0.3), 0 0 0 1px rgba(99,102,241,0.15), 0 8px 24px rgba(99,102,241,0.2)',
        'premium-hover': '0 1px 2px rgba(0,0,0,0.3), 0 0 0 1px rgba(99,102,241,0.25), 0 16px 40px rgba(99,102,241,0.3)',
        'card': '0 0 0 1px rgba(99,102,241,0.06), 0 24px 48px -12px rgba(0,0,0,0.4)',
        'glass': '0 8px 32px rgba(0,0,0,0.4)',
      },
      margin: {
        25: '6.25rem',
        88: '88px',
      },
      top: {
        22: '88px',
      },
      padding: {
        2.5: '0.625rem',
        3: '0.75rem',
        3.5: '0.875rem',
        4: '1rem',
        25: '6.25rem',
      },
      fontSize: {
        /* Ollama typography scale */
        'xs': ['12px', { lineHeight: '16px', letterSpacing: '0' }],
        'sm': ['13px', { lineHeight: '18px', letterSpacing: '0' }],
        'base': ['16px', { lineHeight: '24px', letterSpacing: '0' }],
        'body': ['16px', { lineHeight: '24px', letterSpacing: '0' }],
        'lg': ['18px', { lineHeight: '28px', letterSpacing: '0' }],
        'xl': ['20px', { lineHeight: '24px', letterSpacing: '0' }],
        '2xl': ['24px', { lineHeight: '28px', letterSpacing: '0' }],
        '3xl': ['28px', { lineHeight: '32px', letterSpacing: '0' }],
        '4xl': ['38px', { lineHeight: '40px', letterSpacing: '0' }],
        '5xl': ['56px', { lineHeight: '60px', letterSpacing: '0' }],
        /* Semantic heading sizes */
        'h1': ['56px', { lineHeight: '60px', letterSpacing: '0', fontWeight: '400' }],
        'h2': ['38px', { lineHeight: '40px', letterSpacing: '0', fontWeight: '400' }],
        'h3': ['28px', { lineHeight: '32px', letterSpacing: '0', fontWeight: '400' }],
        'h4': ['24px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '400' }],
        'h5': ['20px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'h6': ['18px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '400' }],
        'h7': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
      },
      width: {
        '8%': '8%',
        '9%': '9%',
        '10%': '10%',
        '11%': '11%',
        '17%': '17%',
        '3/8': '37.5%',
        '36%': '36%',
        '5/8': '62.5%',
        13: '3.25rem',
        18.5: '4.625rem',
        32.5: '8.125rem',
        34: '8.5rem',
        42: '10.5rem',
        45: '11.25rem',
        54: '13.5rem',
        58: '14.5rem',
        62: '15.5rem',
        84: '21rem',
        94: '23.5rem',
        104: '26rem',
        135: '33.75rem',
        244: '61rem',
      },
      minWidth: {
        32.5: '8.125rem',
        34: '8.5rem',
        42: '10.5rem',
        45: '11.25rem',
        54: '13.5rem',
        58: '14.5rem',
        62: '15.5rem',
        84: '21rem',
        94: '23.5rem',
        104: '26rem',
      },
      maxWidth: {
        240: '60rem',
        'prose': '65ch',
        'heading': '45ch',
        'title': '30ch',
        'hero': '20ch',
      },
      fontWeight: {
        light: '300',
        regular: '400',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      letterSpacing: {
        tighter: '-0.02em',
        tight: '-0.01em',
        normal: '0em',
        wide: '0.01em',
        wider: '0.05em',
      },
      lineHeight: {
        none: '1',
        tight: '1.1',
        snug: '1.2',
        normal: '1.5',
        relaxed: '1.7',
        loose: '2',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'out-spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'out-cinema': 'cubic-bezier(0.32, 0.72, 0, 1)',
        'in-expo': 'cubic-bezier(0.7, 0, 0.84, 0)',
      },
      transitionDuration: {
        '400': '400ms',
        '600': '600ms',
        '800': '800ms',
      },
    },
  },
  plugins: [],
};
