CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS dictionary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    resource_name varchar(255) NOT NULL,
    highlighted_text text NOT NULL,
    translated_text text,
    context text,
    extended_context text,
    note varchar(255),
    transcription varchar(255),
    definition text,
    image_url varchar(255),
    status varchar(50) DEFAULT 'new',
    repetition_level integer DEFAULT 0,
    consecutive_success integer DEFAULT 0,
    next_repetition_date date,
    interval float DEFAULT 0,
    ease_factor float DEFAULT 2.5,
    hard_count integer DEFAULT 0,
    lapses integer DEFAULT 0,
    learning_step integer DEFAULT 0,
    learning_due timestamp,
    last_reviewed date,
    total_reviews integer DEFAULT 0,
    correct_reviews integer DEFAULT 0,
    retention_rate float DEFAULT 0.0,
    avg_review_duration integer DEFAULT 0,
    best_review_time time,
    difficulty_score float DEFAULT 0.0,
    is_leech boolean DEFAULT false,
    stability float DEFAULT 0.0,
    retrievability float DEFAULT 0.0,
    rolling_retention float DEFAULT 0.0,
    card_type integer DEFAULT 0,
    embedding vector(384),
    created_on timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS review_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    card_id bigint NOT NULL,
    reviewed_at timestamp NOT NULL,
    rating integer NOT NULL,
    response_time_ms integer NOT NULL,
    stability_before float NOT NULL,
    difficulty_before float NOT NULL,
    elapsed_days float NOT NULL,
    scheduled_days float NOT NULL,
    state varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_srs_parameters (
    user_id uuid PRIMARY KEY,
    w0 float, w1 float, w2 float, w3 float, w4 float, w5 float, 
    w6 float, w7 float, w8 float, w9 float, w10 float, w11 float, w12 float,
    last_optimized timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS outbox_events (
    id UUID PRIMARY KEY,
    aggregate_id VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    topic VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP,
    status VARCHAR(20) NOT NULL
);
